apiVersion: hypernetwork/v1
kind: Environment
metadata:
  name: edge-dmz
spec:
  project: edge-dmz
  domain: edge-dmz.vz.test
  dns:
    enabled: true
    hostResolver: true
    hostListen: 127.0.0.1:15353
    forward:
      enabled: true
      upstream: system
  images:
    ubuntu-base:
      from: ubuntu-latest
      role: base
  networks:
    dmz:
      cidr: 10.80.0.0/24
      mode: shared
      dhcp: false
      natEgress: true
    lan:
      cidr: 10.90.0.0/24
      mode: shared
      dhcp: false
      natEgress: false
  routes:
    - name: dmz-to-lan
      from: dmz
      to: lan
      via: router
  policies:
    - name: dmz-default
      network: dmz
      forward: deny-all
      allow:
        - to: lan
          proto: tcp
          ports:
            - 5432
        - to: dmz
          proto: icmp
          ports: []
    - name: lan-default
      network: lan
      forward: deny-all
      allow: []
  ports:
    - 8080:web:80
  certs:
    enabled: true
    onRotate: reinject
  ingress:
    enabled: true
    bind: 127.0.0.1
    hostAliases: true
    redirectHttp: true
    routes:
      - host: web.svc.edge-dmz.vz.test
        to: web:80
        requires:
          - oidc
      - host: auth.svc.edge-dmz.vz.test
        to: oidc:5556
  oidc:
    enabled: true
    mode: embedded
    issuer: https://auth.svc.edge-dmz.vz.test
    listen: 127.0.0.1:5556
    clients: auto
  vms:
    router:
      from: ubuntu-base
      clone: linked
      dataDisk: 4G
      networks:
        - name: dmz
          ip: 10.80.0.2
        - name: lan
          ip: 10.90.0.2
      cloudInit: cloud-init/router.yaml
      dependsOn: []
      roles:
        - router
      requires: []
      ports: []
      mounts: []
    web:
      from: ubuntu-base
      clone: linked
      dataDisk: 40G
      networks:
        - name: dmz
          ip: 10.80.0.10
      cloudInit: cloud-init/web.yaml
      dependsOn:
        - router
      roles: []
      requires:
        - oidc
      ports: []
      mounts: []
    docker:
      from: ubuntu-base
      clone: linked
      dataDisk: 100G
      networks:
        - name: lan
          ip: 10.90.0.10
      cloudInit: cloud-init/docker.yaml
      dependsOn:
        - router
      roles:
        - docker
      requires: []
      ports: []
      mounts: []
    host:
      from: ubuntu-base
      clone: linked
      dataDisk: 20G
      cpus: 2
      memory: 2048MiB
      networks:
        - name: lan
          ip: 10.90.0.11
      dependsOn: []
      roles: []
      requires: []
      ports: []
      mounts: []
